### ISSUE TITLE
遊戲桌查詢功能

### ISSUE THREAD

**Issue by Dmans** [Dmans/diagonalley-bg-store-system#5]
查詢功能： 

- [x] 可使用以下條件查詢：名稱，店舖，桌子可容納人數

- [x] 查詢必須依據使用者店舖權限

- [x] 查詢結果，如有桌子已經有預約則不顯示“維護”按鈕 （改開 #11 追蹤）

**Comment by Dmans** [comment]
Any update?

**Comment by tom78112** [comment]
請問你的定位預約是遊戲桌狀態嗎?
還是你之後會有另外的欄位去紀錄
因為我看定位的地方好像沒有完成不知道你定位是要怎麼用?

**Comment by Dmans** [comment]
1. 定位預約應該會是在定位資料表裡面有一個欄位紀錄，因為到時候拉資料會以訂位資料表為主
2. 定位部分是舊的，需要經過討論修改舊的定位資料表或改用新的資料表

**Comment by tom78112** [comment]
![image](https://user-images.githubusercontent.com/29017249/27089602-73daf4dc-508d-11e7-8ace-8c996653fd53.png)
