### ISSUE TITLE
薪資計算功能

### ISSUE THREAD

**Issue by Dmans** [Dmans/diagonalley-bg-store-system#8]
工時＊時薪

必須讓使用者多增加時薪欄位

輸出薪資單

新增員工時 email必填

每月審核頁面
- 以店區分

計算時數時超過8小時 以上時數的時薪＊1.33

**Comment by Dmans** [comment]
新增每月審核工讀生薪資 #17

**Comment by Lichiayeh** [comment]
[颱風國定假2倍薪]
如果直接手動輸入2倍的工作時數進去，系統會判定多於8小時後面的數字要計算到加班費上，導致薪資計算錯誤
