### ISSUE TITLE
維護使用者email時，email並未被帶入欄位

### ISSUE THREAD

**Issue by Dmans** [Dmans/diagonalley-bg-store-system#9]
維護使用者畫面
<img width="398" alt="2017-06-09 12 46 20" src="https://user-images.githubusercontent.com/14008567/26940428-28715a2e-4cad-11e7-80ab-82551252010e.png">

資料庫資料
<img width="629" alt="2017-06-09 12 48 13" src="https://user-images.githubusercontent.com/14008567/26940489-674aa02a-4cad-11e7-914c-01ca4a2553b5.png">

**Comment by tom78112** [comment]
已修正
